/**
 * Missouri presidential county plurality winners.
 * 1888: Political Graveyard (St. Louis → St. Louis County; St. Louis city → St. Louis City).
 * 1892: Wikipedia county table (Dave Leip / Géoelections).
 * 2024: Wikipedia county table (Missouri Secretary of State).
 * 1884 county plurality is unpublished on Political Graveyard (“No data” for every county).
 */

export const PRES_1888_DEM = [
  "Audrain",
  "Barry",
  "Barton",
  "Bates",
  "Bollinger",
  "Boone",
  "Buchanan",
  "Butler",
  "Callaway",
  "Carter",
  "Cass",
  "Cedar",
  "Chariton",
  "Clark",
  "Clay",
  "Clinton",
  "Cole",
  "Cooper",
  "Daviess",
  "Dent",
  "Dunklin",
  "Gentry",
  "Henry",
  "Howard",
  "Howell",
  "Iron",
  "Jackson",
  "Jefferson",
  "Johnson",
  "Knox",
  "Lafayette",
  "Lewis",
  "Lincoln",
  "Linn",
  "Livingston",
  "Macon",
  "Madison",
  "Maries",
  "Marion",
  "McDonald",
  "Mississippi",
  "Monroe",
  "Montgomery",
  "Morgan",
  "New Madrid",
  "Newton",
  "Oregon",
  "Pemiscot",
  "Perry",
  "Phelps",
  "Pike",
  "Platte",
  "Pulaski",
  "Ralls",
  "Randolph",
  "Ray",
  "Reynolds",
  "Ripley",
  "St. Clair",
  "St. Francois",
  "Ste. Genevieve",
  "Saline",
  "Schuyler",
  "Scotland",
  "Scott",
  "Shannon",
  "Shelby",
  "Stoddard",
  "Texas",
  "Vernon",
  "Washington",
  "Wayne",
  "Worth",
];

export const PRES_1888_GOP = [
  "Adair",
  "Andrew",
  "Atchison",
  "Benton",
  "Caldwell",
  "Camden",
  "Cape Girardeau",
  "Carroll",
  "Christian",
  "Crawford",
  "Dade",
  "Dallas",
  "DeKalb",
  "Douglas",
  "Franklin",
  "Gasconade",
  "Greene",
  "Grundy",
  "Harrison",
  "Hickory",
  "Holt",
  "Jasper",
  "Laclede",
  "Lawrence",
  "Mercer",
  "Miller",
  "Moniteau",
  "Nodaway",
  "Osage",
  "Ozark",
  "Pettis",
  "Polk",
  "Putnam",
  "St. Charles",
  "St. Louis County",
  "St. Louis City",
  "Stone",
  "Sullivan",
  "Taney",
  "Warren",
  "Webster",
  "Wright",
];

/** Harrison plurality, 1892 Wikipedia county table. Remaining counties: Cleveland. */
export const PRES_1892_GOP = [
  "Adair",
  "Andrew",
  "Barry",
  "Benton",
  "Caldwell",
  "Camden",
  "Cape Girardeau",
  "Cedar",
  "Christian",
  "Crawford",
  "Dade",
  "Dallas",
  "Douglas",
  "Franklin",
  "Gasconade",
  "Greene",
  "Grundy",
  "Harrison",
  "Hickory",
  "Holt",
  "Jasper",
  "Laclede",
  "Lawrence",
  "Mercer",
  "Miller",
  "Osage",
  "Ozark",
  "Polk",
  "Putnam",
  "St. Charles",
  "St. Louis County",
  "St. Louis City",
  "Stone",
  "Sullivan",
  "Taney",
  "Warren",
  "Webster",
  "Wright",
];

export const PRES_1892_DEM = [
  "Atchison",
  "Audrain",
  "Barton",
  "Bates",
  "Bollinger",
  "Boone",
  "Buchanan",
  "Butler",
  "Callaway",
  "Carroll",
  "Carter",
  "Cass",
  "Chariton",
  "Clark",
  "Clay",
  "Clinton",
  "Cole",
  "Cooper",
  "Daviess",
  "DeKalb",
  "Dent",
  "Dunklin",
  "Gentry",
  "Henry",
  "Howard",
  "Howell",
  "Iron",
  "Jackson",
  "Jefferson",
  "Johnson",
  "Knox",
  "Lafayette",
  "Lewis",
  "Lincoln",
  "Linn",
  "Livingston",
  "Macon",
  "Madison",
  "Maries",
  "Marion",
  "McDonald",
  "Mississippi",
  "Moniteau",
  "Monroe",
  "Montgomery",
  "Morgan",
  "New Madrid",
  "Newton",
  "Nodaway",
  "Oregon",
  "Pemiscot",
  "Perry",
  "Pettis",
  "Phelps",
  "Pike",
  "Platte",
  "Pulaski",
  "Ralls",
  "Randolph",
  "Ray",
  "Reynolds",
  "Ripley",
  "St. Clair",
  "St. Francois",
  "Ste. Genevieve",
  "Saline",
  "Schuyler",
  "Scotland",
  "Scott",
  "Shannon",
  "Shelby",
  "Stoddard",
  "Texas",
  "Vernon",
  "Washington",
  "Wayne",
  "Worth",
];

/** Harris counties, 2024. Remaining: Trump. Wiki “St. Louis” = St. Louis County. */
export const PRES_2024_DEM = ["Boone", "Jackson", "St. Louis County", "St. Louis City"];

export const PRES_2024_GOP = [
  "Adair",
  "Andrew",
  "Atchison",
  "Audrain",
  "Barry",
  "Barton",
  "Bates",
  "Benton",
  "Bollinger",
  "Buchanan",
  "Butler",
  "Caldwell",
  "Callaway",
  "Camden",
  "Cape Girardeau",
  "Carroll",
  "Carter",
  "Cass",
  "Cedar",
  "Chariton",
  "Christian",
  "Clark",
  "Clay",
  "Clinton",
  "Cole",
  "Cooper",
  "Crawford",
  "Dade",
  "Dallas",
  "Daviess",
  "DeKalb",
  "Dent",
  "Douglas",
  "Dunklin",
  "Franklin",
  "Gasconade",
  "Gentry",
  "Greene",
  "Grundy",
  "Harrison",
  "Henry",
  "Hickory",
  "Holt",
  "Howard",
  "Howell",
  "Iron",
  "Jasper",
  "Jefferson",
  "Johnson",
  "Knox",
  "Laclede",
  "Lafayette",
  "Lawrence",
  "Lewis",
  "Lincoln",
  "Linn",
  "Livingston",
  "Macon",
  "Madison",
  "Maries",
  "Marion",
  "McDonald",
  "Mercer",
  "Miller",
  "Mississippi",
  "Moniteau",
  "Monroe",
  "Montgomery",
  "Morgan",
  "New Madrid",
  "Newton",
  "Nodaway",
  "Oregon",
  "Osage",
  "Ozark",
  "Pemiscot",
  "Perry",
  "Pettis",
  "Phelps",
  "Pike",
  "Platte",
  "Polk",
  "Pulaski",
  "Putnam",
  "Ralls",
  "Randolph",
  "Ray",
  "Reynolds",
  "Ripley",
  "St. Charles",
  "St. Clair",
  "St. Francois",
  "Ste. Genevieve",
  "Saline",
  "Schuyler",
  "Scotland",
  "Scott",
  "Shannon",
  "Shelby",
  "Stoddard",
  "Stone",
  "Sullivan",
  "Taney",
  "Texas",
  "Vernon",
  "Warren",
  "Washington",
  "Wayne",
  "Webster",
  "Worth",
  "Wright",
];
